server:
  port: 80
  servlet:
    encoding:
      charset: utf-8
      force: true
  error:
    include-exception: true
    include-stacktrace: always
    whitelabel:
      enabled: false

spring:
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: false
    view:
      prefix: /WEB-INF/view/ # jsp 파일 경로
      suffix: .jsp # 확장자
    hiddenmethod:
      filter:
        enabled: true # update, delete put방식으로 보내기 위한 설정
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    url: jdbc:mysql://database-1.chyqscqk4zrv.ap-northeast-2.rds.amazonaws.com:3306/cyberuniv?serverTimeZone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: Asd123456789!
    
mybatis:
  mapper-locations:
    - classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true # DB의 underscore(snake case) 방식을 Java의 camel case 방식과 매핑


